# Generated by Django 5.2.7 on 2025-10-29 20:22

import chatter.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Message body')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatter_messages', to='hr.employee')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatter_messages', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chatter_messages', to='base.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatter_messages', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'chatter_message',
                'ordering': ('-created_at',),
                'permissions': [('post_chatter_message', 'Can post chatter message'), ('delete_own_chatter_message', 'Can delete own chatter message')],
            },
        ),
        migrations.CreateModel(
            name='ChatterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chatter.models.chatter_attachment_upload_to)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('mimetype', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chatter.chattermessage')),
            ],
            options={
                'db_table': 'chatter_attachment',
                'ordering': ('message_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChatterFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chatter_followers', to='base.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatter_followers', to='contenttypes.contenttype')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatter_follower',
                'ordering': ('content_type_id', 'object_id', 'id'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='chat_fol_ct_oid_idx'), models.Index(fields=['company'], name='chat_fol_company_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('employee__isnull', False), _connector='OR'), name='chat_fol_has_actor'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('content_type', 'object_id', 'user'), name='chat_fol_unique_user'), models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('content_type', 'object_id', 'employee'), name='chat_fol_unique_employee')],
            },
        ),
        migrations.AddIndex(
            model_name='chattermessage',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='chat_msg_ct_oid_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='chattermessage',
            index=models.Index(fields=['company', 'created_at'], name='chat_msg_comp_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='chattermessage',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='chat_msg_body_not_empty'),
        ),
        migrations.AddIndex(
            model_name='chatterattachment',
            index=models.Index(fields=['message'], name='chat_att_msg_idx'),
        ),
    ]
