# Generated by Django 5.2.7 on 2025-11-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatterfollower',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='chattermessage',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
