# Generated by Django 5.2.7 on 2025-11-02 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_partner_partner_comp_iscomp_name_idx'),
        ('chatter', '0002_alter_chatterfollower_object_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chattermessage',
            constraint=models.CheckConstraint(condition=models.Q(('author_user__isnull', False), ('author_employee__isnull', False), _connector='OR'), name='chat_msg_has_actor'),
        ),
    ]
