# Generated by Django 5.2.7 on 2025-10-25 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('parent_path', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Parent path')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='base.company', verbose_name='Company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.assetcategory', verbose_name='Parent')),
            ],
            options={
                'db_table': 'assets_category',
                'ordering': ('company_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='Code')),
                ('serial', models.CharField(blank=True, default='', max_length=128, verbose_name='Serial number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], db_index=True, default='available', max_length=16, verbose_name='Status')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase value')),
                ('note', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hr.department', verbose_name='Department')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_assets', to='hr.employee', verbose_name='Holder (employee)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset', verbose_name='Parent Asset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory', verbose_name='Category')),
            ],
            options={
                'db_table': 'assets_asset',
                'ordering': ('company_id', 'name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='From')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='To')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset', verbose_name='Asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='base.company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'db_table': 'assets_assignment',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['company', 'active'], name='as_asg_c_act_idx'), models.Index(fields=['asset', 'employee'], name='as_asg_ast_emp_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['company', 'active'], name='as_cat_c_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='as_cat_comp_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'active'], name='as_ast_c_act_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'status'], name='as_ast_c_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='as_ast_comp_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('company', 'serial'), name='as_ast_comp_serial_uniq'),
        ),
    ]
