# Generated by Django 5.2.7 on 2025-10-09 00:43

import base.models.managers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('asset_tag', models.CharField(max_length=64)),
                ('serial_no', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('assigned', 'Assigned'), ('repair', 'Repair'), ('lost', 'Lost'), ('scrapped', 'Scrapped')], db_index=True, default='in_stock', max_length=16)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, help_text='Override type default', null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'emp_asset_item',
                'ordering': ['model__type__name', 'model__name', 'asset_tag'],
                'permissions': [('assign_item', 'Can assign asset item'), ('return_item', 'Can return asset item'), ('transfer_item', 'Can transfer asset item')],
            },
            managers=[
                ('objects', base.models.managers.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('manufacturer', models.CharField(blank=True, max_length=128)),
                ('sku', models.CharField(blank=True, help_text='Manufacturer SKU / Part Number if applicable.', max_length=128)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text="Arbitrary specs (e.g., {'cpu':'i7','ram':'16GB','ssd':'512GB'}).")),
                ('sequence', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(blank=True, max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/models/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'emp_asset_model',
                'ordering': ['type__name', 'sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('code', models.SlugField(help_text="Unique code/slug for referencing in integrations (e.g., 'laptop', 'phone').", max_length=64, unique=True)),
                ('default_warranty_months', models.PositiveIntegerField(default=0, help_text='Default warranty for items of this type (months). Can be overridden on the item.')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name (for UI only).', max_length=64)),
            ],
            options={
                'db_table': 'emp_asset_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_assigned', models.DateField()),
                ('due_back', models.DateField(blank=True, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_overdue', models.BooleanField(db_index=True, default=False)),
                ('handover_note', models.TextField(blank=True)),
                ('return_note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'emp_asset_assignment',
                'ordering': ['-date_assigned'],
            },
            managers=[
                ('objects', base.models.managers.CompanyScopeManager()),
            ],
        ),
    ]
