# Generated by Django 5.2.7 on 2025-11-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='Code')),
                ('serial', models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], db_index=True, default='available', max_length=16, verbose_name='Status')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase value')),
                ('note', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'db_table': 'assets_asset',
                'ordering': ('company_id', 'name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='From')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='To')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'assets_assignment',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('parent_path', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Parent path')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'assets_category',
                'ordering': ('company_id', 'name'),
            },
        ),
    ]
