# Generated by Django 5.2.7 on 2025-10-29 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='base.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hr.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='asset',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holding_assets', to='hr.employee', verbose_name='Holder (employee)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset', verbose_name='Parent Asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='base.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='hr.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='base.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.assetcategory', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory', verbose_name='Category'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['company', 'active'], name='as_asg_c_act_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['asset', 'employee'], name='as_asg_ast_emp_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__isnull', True), ('date_from__isnull', True), ('date_to__gte', models.F('date_from')), _connector='OR'), name='as_asg_dates_chk'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('date_to__isnull', True)), fields=('asset',), name='as_asg_one_open_per_asset'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['company', 'active'], name='as_cat_c_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='as_cat_comp_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('pk')), _negated=True), name='as_cat_parent_not_self_chk'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'active'], name='as_ast_c_act_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'status'], name='as_ast_c_st_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'holder'], name='as_ast_c_holder_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='as_ast_comp_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('serial__isnull', False), models.Q(('serial', ''), _negated=True)), fields=('company', 'serial'), name='as_ast_comp_serial_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('holder__isnull', False), ('status', 'assigned')), models.Q(('status', 'assigned'), _negated=True), _connector='OR'), name='as_ast_status_holder_chk'),
        ),
    ]
