# Generated by Django 5.2.7 on 2025-10-25 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('holder__isnull', False), ('status', 'assigned')), models.Q(('status', 'assigned'), _negated=True), _connector='OR'), name='as_ast_status_holder_chk'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__isnull', True), ('date_from__isnull', True), ('date_to__gte', models.F('date_from')), _connector='OR'), name='as_asg_dates_chk'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('date_to__isnull', True)), fields=('asset',), name='as_asg_one_open_per_asset'),
        ),
    ]
