# Generated by Django 5.2.7 on 2025-10-09 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company'),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='current_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assets', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assets.assetmodel'),
        ),
        migrations.AddIndex(
            model_name='assettype',
            index=models.Index(fields=['active'], name='asset_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='assettype',
            index=models.Index(fields=['name'], name='asset_type_name_idx'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.assetitem'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['company', 'status'], name='emp_asset_i_company_88830e_idx'),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['company', 'serial_no'], name='emp_asset_i_company_724311_idx'),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['company', 'warranty_expiry'], name='emp_asset_i_company_21f2df_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetitem',
            constraint=models.UniqueConstraint(fields=('company', 'asset_tag'), name='uniq_asset_tag_per_company'),
        ),
        migrations.AddIndex(
            model_name='assetmodel',
            index=models.Index(fields=['active'], name='asset_model_active_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmodel',
            index=models.Index(fields=['type', 'name'], name='asset_model_type_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetmodel',
            constraint=models.UniqueConstraint(fields=('type', 'name'), name='uniq_asset_model_type_name'),
        ),
        migrations.AddConstraint(
            model_name='assetmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('manufacturer__gt', ''), ('sku__gt', '')), fields=('type', 'manufacturer', 'sku'), name='uniq_asset_model_type_mfr_sku'),
        ),
        migrations.AddIndex(
            model_name='employeeasset',
            index=models.Index(fields=['company', 'is_active'], name='emp_asset_a_company_df7003_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeasset',
            index=models.Index(fields=['company', 'employee', 'is_active'], name='emp_asset_a_company_ff93a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeasset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('item',), name='uniq_active_assignment_per_item'),
        ),
    ]
