# Generated by Django 5.2.6 on 2025-09-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_items', to='base.company'),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='current_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_asset', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.assetitem'),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['company', 'status'], name='emp_asset_i_company_88830e_idx'),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['model', 'serial_no'], name='emp_asset_i_model_i_36f063_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetmodel',
            unique_together={('type', 'name')},
        ),
        migrations.AddConstraint(
            model_name='employeeasset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('item',), name='uniq_active_assignment_per_item'),
        ),
    ]
