# Generated by Django 5.2.7 on 2025-11-01 20:39

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='asset',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='assetassignment',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='assetcategory',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
    ]
