# Generated by Django 5.2.7 on 2025-10-25 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_as_ast_status_holder_chk_and_more'),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='as_ast_comp_serial_uniq',
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial number'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('serial__isnull', False)), fields=('company', 'serial'), name='as_ast_comp_serial_uniq'),
        ),
    ]
