# Generated by Django 5.2.7 on 2026-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assetcategory_managers'),
        ('base', '0010_alter_company_parent'),
        ('hr', '0013_employeeeducation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetassignment',
            name='as_asg_one_open_per_asset',
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('date_to__isnull', True)), fields=('asset',), name='as_asg_one_open_per_asset'),
        ),
    ]
