# Generated by Django 5.2.7 on 2025-10-25 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_updated_by'),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'holder'], name='as_ast_c_holder_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('pk')), _negated=True), name='as_cat_parent_not_self_chk'),
        ),
    ]
