# Generated by Django 5.2.7 on 2025-10-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_as_ast_c_holder_idx_and_more'),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetcategory',
            name='as_cat_parent_not_self_chk',
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['asset', 'date_to'], name='as_asg_asset_open_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='as_cat_parent_not_self_chk'),
        ),
    ]
