# Generated by Django 5.2.7 on 2025-10-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_assetcategory_as_cat_parent_not_self_chk_and_more'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetcategory',
            name='as_cat_parent_not_self_chk',
        ),
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='as_asg_asset_open_idx',
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('pk')), _negated=True), name='as_cat_parent_not_self_chk'),
        ),
    ]
