# Generated by Django 5.2.7 on 2026-01-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_normalize_assetassignment_before_remove_active'),
        ('base', '0010_alter_company_parent'),
        ('hr', '0013_employeeeducation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetassignment',
            name='as_asg_one_open_per_asset',
        ),
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='as_asg_c_act_idx',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='active',
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['company'], name='as_asg_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('date_to__isnull', True)), fields=('asset',), name='as_asg_one_open_per_asset'),
        ),
    ]
