# Generated by Django 5.2.7 on 2026-01-12 20:29

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_assetassignment_as_asg_one_open_per_asset_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assetcategory',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
    ]
