# Generated by Django 5.2.6 on 2025-09-28 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='uniq_user_per_company',
        ),
        migrations.AlterField(
            model_name='employee',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['active'], name='hr_employee_active_63ec35_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='hr_employee_departm_1b8ba9_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('company', 'barcode'), name='uniq_employee_barcode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('manager')), _negated=True), name='employee_manager_not_self'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('coach')), _negated=True), name='employee_coach_not_self'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('pin__gt', '')), fields=('company', 'pin'), name='uniq_employee_pin_per_company'),
        ),
    ]
