# Generated by Django 5.2.7 on 2025-11-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('approve_employee', 'Can approve employee record'), ('view_private_fields', 'Can view employee private fields'), ('manage_all_hr', 'Can manage all HR records (company-wide)'), ('manage_department_hr', 'Can manage HR records for own departments')]},
        ),
    ]
