# Generated by Django 5.2.7 on 2025-10-31 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshift',
            options={'ordering': ('company', 'name')},
        ),
        migrations.RemoveConstraint(
            model_name='workshift',
            name='uniq_ws_company_name_no_dept',
        ),
        migrations.RemoveConstraint(
            model_name='workshift',
            name='uniq_ws_company_dept_name',
        ),
        migrations.RemoveIndex(
            model_name='workshift',
            name='hr_ws_comp_dept_name_idx',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='department',
        ),
        migrations.AddIndex(
            model_name='workshift',
            index=models.Index(fields=['company', 'name'], name='hr_ws_comp_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_ws_company_name'),
        ),
    ]
