# Generated by Django 5.2.7 on 2025-11-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                # الرجوع إلى manager افتراضي فقط
                ('objects', models.Manager()),
            ],
        ),
    ]
