# Generated by Django 5.2.6 on 2025-09-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_employee_uniq_user_per_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='certificate',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='private_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='private_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='study_field',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='study_school',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
