# Generated by Django 5.2.7 on 2025-11-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                # Manager افتراضي فقط (بدون ACL وبدون Scope)
                ('objects', models.Manager()),
            ],
        ),
    ]
