# Generated by Django 5.2.7 on 2025-11-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
                # الرجوع إلى manager افتراضي فقط
                ('objects', models.Manager()),
            ],
        ),
    ]
