# Generated by Django 5.2.7 on 2025-11-13 13:52

import base.acl
import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
                ('acl_objects', base.acl.ACLManager()),
            ],
        ),
    ]
