# Generated by Django 5.2.7 on 2025-12-12 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0005_alter_department_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company'),
        ),
    ]
