# Generated by Django 5.2.7 on 2025-12-19 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0007_department_uniq_department_per_company_parent_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='hr_employee_user_uniq',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('user__isnull', False)), fields=('user',), name='hr_employee_user_uniq_active'),
        ),
    ]
