# Generated by Django 5.2.7 on 2025-12-20 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0008_remove_employee_hr_employee_user_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='uniq_department_per_company_parent_name',
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('company', 'name'), name='uniq_department_root_per_company_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('company', 'parent', 'name'), name='uniq_department_per_company_parent_name'),
        ),
    ]
