# Generated by Django 5.2.7 on 2025-12-31 14:56

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0010_remove_employee_hr_employee_user_uniq_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=10)),
                ('is_active_flag', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employee Status',
                'verbose_name_plural': 'Employee Statuses',
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Short reason for status change', max_length=255)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Employee Status History',
                'verbose_name_plural': 'Employee Status History',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='uniq_employee_barcode',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='employee_manager_not_self',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='employee_coach_not_self',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='uniq_employee_pin_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='hr_employee_unique_work_contact',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_employee_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_emp_comp_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_emp_comp_workct_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_emp_comp_pin_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_emp_comp_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_company_7423fa_idx',
            old_name='hr_employee_company_active_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_name_5fd823_idx',
            old_name='hr_employee_name_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_departm_1b8ba9_idx',
            old_name='hr_employee_departm_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birthday_public_display_string',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='coach_id_cache',
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='car',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_contact',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_work_contact', to='base.partner'),
        ),
        migrations.AddField(
            model_name='employeestatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeestatushistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeestatushistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_history', to='hr.employeestatus'),
        ),
    ]
