# Generated by Django 5.2.7 on 2025-12-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_employeestatus_employeestatushistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.employeestatus'),
        ),
    ]
