# Generated by Django 5.2.7 on 2025-12-31 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_employee_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('certificate', models.CharField(blank=True, help_text='Degree or certificate name', max_length=128)),
                ('field_of_study', models.CharField(blank=True, max_length=128)),
                ('institution', models.CharField(blank=True, help_text='School / University / Institute', max_length=255)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_employee_education',
                'ordering': ['-end_year', '-start_year'],
                'indexes': [models.Index(fields=['employee'], name='hr_employee_employe_843686_idx')],
            },
        ),
    ]
