# Generated by Django 5.2.7 on 2026-01-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0013_employeeeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_career_paths', to='base.company')),
                ('from_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_next_steps', to='hr.job')),
                ('to_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_prev_steps', to='hr.job')),
            ],
            options={
                'db_table': 'hr_job_career_path',
                'ordering': ('company__name', 'from_job__name', 'sequence', 'to_job__name'),
                'indexes': [models.Index(fields=['company', 'active'], name='jobcp_co_act_idx'), models.Index(fields=['company', 'from_job', 'active'], name='jobcp_co_from_act')],
                'constraints': [models.UniqueConstraint(fields=('company', 'from_job', 'to_job'), name='jobcareerpath_unique_step'), models.CheckConstraint(condition=models.Q(('from_job', models.F('to_job')), _negated=True), name='jobcareerpath_no_self_loop_chk')],
            },
        ),
    ]
