# Generated by Django 5.2.7 on 2026-01-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_jobcareerpath'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcareerpath',
            options={'ordering': ('from_job__name', 'sequence', 'to_job__name')},
        ),
        migrations.RemoveConstraint(
            model_name='jobcareerpath',
            name='jobcareerpath_unique_step',
        ),
        migrations.RemoveConstraint(
            model_name='jobcareerpath',
            name='jobcareerpath_no_self_loop_chk',
        ),
        migrations.RemoveIndex(
            model_name='jobcareerpath',
            name='jobcp_co_act_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobcareerpath',
            name='jobcp_co_from_act',
        ),
        migrations.RemoveField(
            model_name='jobcareerpath',
            name='company',
        ),
        migrations.AddField(
            model_name='jobcareerpath',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcareerpath',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcareerpath',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobcareerpath',
            name='from_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths_from', to='hr.job'),
        ),
        migrations.AlterField(
            model_name='jobcareerpath',
            name='sequence',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='jobcareerpath',
            name='to_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_paths_to', to='hr.job'),
        ),
        migrations.AddConstraint(
            model_name='jobcareerpath',
            constraint=models.UniqueConstraint(fields=('from_job', 'to_job'), name='jobcareerpath_unique_transition'),
        ),
        migrations.AlterModelTable(
            name='jobcareerpath',
            table=None,
        ),
    ]
