# Generated by Django 5.2.7 on 2026-01-08 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0017_careerpolicyauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpolicy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_policies', to='base.company'),
        ),
        migrations.AddConstraint(
            model_name='careerpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('company',), name='one_active_career_policy_per_company'),
        ),
    ]
