# Generated by Django 5.2.7 on 2026-01-08 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0018_careerpolicy_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_policies', to='base.company'),
        ),
    ]
