# Generated by Django 5.2.7 on 2026-01-08 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0019_alter_careerpolicy_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('snapshot_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('near_ready', 'Near Ready'), ('not_ready', 'Not Ready')], db_index=True, default='not_ready', max_length=16)),
                ('fit_score', models.PositiveSmallIntegerField(default=0)),
                ('blocking_reason', models.CharField(blank=True, default='', max_length=64)),
                ('blocking_factors', models.JSONField(blank=True, default=list)),
                ('policy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_readiness_snapshots', to='base.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to='hr.employee')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_readiness_snapshots', to='hr.job')),
            ],
            options={
                'ordering': ('-snapshot_date', '-id'),
                'indexes': [models.Index(fields=['company', 'snapshot_date'], name='hr_employee_company_c50b22_idx'), models.Index(fields=['employee', 'snapshot_date'], name='hr_employee_employe_d073ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'snapshot_date'), name='readinesssnapshot_unique_employee_date')],
            },
        ),
    ]
