# Generated by Django 5.2.7 on 2026-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0020_employeereadinesssnapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeereadinesssnapshot',
            name='readinesssnapshot_unique_employee_date',
        ),
        migrations.AddConstraint(
            model_name='employeereadinesssnapshot',
            constraint=models.UniqueConstraint(fields=('employee', 'job', 'snapshot_date'), name='readinesssnapshot_unique_employee_job_date'),
        ),
    ]
