# Generated by Django 5.2.7 on 2026-01-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_alter_employeeeducation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeeducation',
            options={'ordering': ['-end_year', '-start_year']},
        ),
        migrations.RenameIndex(
            model_name='employeeeducation',
            new_name='hr_employee_employe_843686_idx',
            old_name='hr_edu_employee_idx',
        ),
    ]
