# Generated by Django 5.2.7 on 2026-01-12 21:45

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_alter_employeeeducation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
    ]
