# Generated by Django 5.2.7 on 2025-11-29 16:26

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0005_alter_department_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('overall_score_pct', models.PositiveIntegerField(default=0, help_text='Aggregated score of rating items (0..100).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ratings', to='hr.employee')),
                ('rated_by', models.ForeignKey(blank=True, help_text='Usually the direct manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_daily_ratings', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_daily_rating',
                'ordering': ['-date', 'employee'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyRatingFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight_pct', models.PositiveIntegerField(default=100, help_text='Weight inside daily rating aggregation (0..100).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_daily_rating_factor',
                'ordering': ['company', 'name'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyRatingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('score_pct', models.PositiveIntegerField(default=0, help_text='0..100')),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('daily_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='performance.dailyrating')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_items', to='performance.dailyratingfactor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_daily_rating_item',
            },
        ),
        migrations.CreateModel(
            name='EmployeeObjectiveScoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('tasks_weight_pct', models.PositiveIntegerField(default=30, help_text='Weight for Tasks Progress (0..100).')),
                ('kpi_weight_pct', models.PositiveIntegerField(default=30, help_text='Weight for KPI Score (0..100).')),
                ('timeliness_weight_pct', models.PositiveIntegerField(default=15, help_text='Weight for Timeliness (0..100).')),
                ('efficiency_weight_pct', models.PositiveIntegerField(default=10, help_text='Weight for Time Efficiency (0..100).')),
                ('quality_weight_pct', models.PositiveIntegerField(default=15, help_text='Weight for Tasks Quality (0..100).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_employee_objective_scoring_policy',
                'ordering': ('company', 'name'),
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('overall_rating', models.CharField(blank=True, max_length=32)),
                ('calibration_notes', models.TextField(blank=True)),
                ('final_score_pct', models.PositiveIntegerField(db_index=True, default=0)),
                ('calibrated_score_pct', models.PositiveIntegerField(blank=True, help_text='Final calibrated score (0..100). If null, use final_score_pct.', null=True)),
                ('calibration_reason', models.TextField(blank=True, help_text='Reason for calibration / normalization.')),
                ('calibration_applied_at', models.DateTimeField(blank=True, help_text='When calibration was applied.', null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('calibrated', 'Calibrated'), ('approved', 'Approved'), ('locked', 'Locked')], db_index=True, default='draft', max_length=12)),
                ('current_step', models.PositiveIntegerField(default=0, help_text='الخطوة الحالية داخل Workflow.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_evaluations', to='hr.employee')),
                ('calibrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrated_evaluations', to='hr.employee')),
                ('calibration_applied_by', models.ForeignKey(blank=True, help_text='Who applied the calibration (usually manager/HR).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_evaluation_calibrations', to='hr.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_approver', models.ForeignKey(blank=True, help_text='الموظف المطلوب منه اعتماد الخطوة الحالية.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_pending_approval', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='hr.employee')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_evaluations', to='hr.employee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_evaluation',
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.CreateModel(
            name='EvaluationCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('old_score_pct', models.PositiveIntegerField(help_text='Evaluation final_score_pct before calibration.')),
                ('new_score_pct', models.PositiveIntegerField(help_text='Calibrated score (0..100).')),
                ('reason', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_calibrations', to='hr.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='performance.evaluation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_evaluation_calibration',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('role', models.CharField(choices=[('self', 'Self'), ('manager', 'Direct Manager'), ('peer', 'Peer / Colleague'), ('skip_manager', 'Skip-level Manager'), ('hr', 'HR'), ('other', 'Other')], default='manager', max_length=16)),
                ('overall_score_pct', models.PositiveIntegerField(default=0, help_text='Overall feedback score (0..100).')),
                ('comment', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='performance.evaluation')),
                ('from_employee', models.ForeignKey(blank=True, help_text='Employee giving the feedback (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedbacks', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_evaluation_feedback',
                'ordering': ['evaluation', '-created_at'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('weight_pct', models.PositiveIntegerField(help_text='0..100')),
                ('source_kind', models.CharField(choices=[('objective_score', 'Objective Score (score_pct)'), ('objective_progress', 'Objective Progress (progress_pct)'), ('kpi_score', 'KPI Score (score_pct)'), ('tasks_progress', 'Tasks Progress (avg % complete)'), ('external_metric', 'External Metric (model/field/filter)'), ('manual', 'Manual Entry (default)'), ('daily_rating', 'Daily Rating (avg overall score)'), ('temp_tasks_load', 'Temporary Tasks Load Index'), ('temp_tasks_score', 'Temporary Tasks Performance Score'), ('employee_objective_score', 'Employee Objective Contribution Score'), ('employee_objective_timeliness', 'Employee Objective Timeliness (Tasks Due/Done)'), ('employee_objective_efficiency', 'Employee Objective Time Efficiency'), ('employee_objective_quality', 'Employee Objective Tasks Quality'), ('quality_score', 'Quality / Mistakes / Complaints Score'), ('feedback_score', '360° Feedback (Self/Manager/Peers)')], default='manual', max_length=32)),
                ('external_model', models.CharField(blank=True, help_text="e.g. 'attendance.AttendanceLog'", max_length=128)),
                ('external_field', models.CharField(blank=True, help_text="Field to aggregate (e.g., 'worked_minutes')", max_length=64)),
                ('external_aggregation', models.CharField(blank=True, choices=[('sum', 'Sum'), ('avg', 'Average'), ('latest', 'Latest')], default='', help_text='How to combine values', max_length=16)),
                ('external_filter', models.JSONField(blank=True, default=dict, help_text='Optional filter JSON (key->value)')),
                ('manual_default_score_pct', models.PositiveIntegerField(default=0, help_text='Default 0..100')),
                ('min_score_pct', models.PositiveIntegerField(default=0)),
                ('max_score_pct', models.PositiveIntegerField(default=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_evaluation_parameter',
                'ordering': ['template', 'name'],
                'permissions': [('reorder_parameters', 'Can reorder evaluation parameters')],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationParameterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('raw_value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('raw_value_json', models.JSONField(blank=True, null=True)),
                ('score_pct', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_results', to='performance.evaluation')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='performance.evaluationparameter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_evaluation_parameter_result',
                'permissions': [('rate_parameter_result', 'Can rate parameter result')],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_templates', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_evaluation_template',
                'ordering': ['company', 'name'],
                'permissions': [('use_evaluation_template', 'Can use evaluation template'), ('manage_template_parameters', 'Can manage template parameters')],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AddField(
            model_name='evaluationparameter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='performance.evaluationtemplate'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='performance.evaluationtemplate'),
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True, default=10)),
                ('frequency_label', models.CharField(blank=True, help_text='وصف حر للتكرار (مثلاً: Monthly / Quarterly / Project-based).', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_evaluation_type',
                'ordering': ('company', 'sequence', 'name'),
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True, default=10, help_text='ترتيب الخطوة داخل سير الموافقات (كلما قل الرقم كانت الخطوة أبكر).')),
                ('approver_kind', models.CharField(choices=[('direct_manager', 'Direct Manager'), ('department_manager', 'Department Manager'), ('manager_chain', 'Manager Chain (Level)'), ('employee', 'Specific Employee'), ('group', 'Specific Group/Role')], default='direct_manager', max_length=32)),
                ('manager_level', models.PositiveSmallIntegerField(default=1, help_text='يُستخدم فقط عند اختيار MANAGER_CHAIN لتحديد مستوى المدير في السلسلة.')),
                ('description', models.TextField(blank=True)),
                ('approver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps_as_specific_approver', to='hr.employee')),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_approval_steps', to='auth.group')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='performance.evaluationtype')),
            ],
            options={
                'db_table': 'perf_evaluation_approval_step',
                'ordering': ('company', 'evaluation_type', 'sequence', 'id'),
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_type',
            field=models.ForeignKey(blank=True, help_text='نوع التقييم (شهري، ربع سنوي، سنوي، أو حسب ما تُعرّفه من الـ Admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='performance.evaluationtype'),
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('#', 'Count'), ('%', 'Percent'), ('IQD', 'IQD'), ('USD', 'USD'), ('hrs', 'Hours'), ('min', 'Minutes'), ('custom', 'Custom')], default='#', max_length=10)),
                ('higher_is_better', models.BooleanField(default=True, help_text='If False, lower values score higher')),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('weight_pct', models.PositiveIntegerField(default=100)),
                ('attainment_pct', models.PositiveIntegerField(db_index=True, default=0, help_text='0..100% of target achieved')),
                ('score_pct', models.PositiveIntegerField(default=0, help_text='0..100 normalized score')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpis', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_kpi',
                'permissions': [('recompute_kpi', 'Can recompute KPI'), ('set_kpi_manual_value', 'Can set manual KPI value')],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.AddField(
            model_name='evaluationparameter',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_params', to='performance.kpi'),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('hierarchy_level', models.PositiveIntegerField(default=1, help_text='1 = Company, 2 = Division, 3 = Department, 4 = Section, 5 = Team, 6 = Employee')),
                ('rollup_strategy', models.CharField(choices=[('average', 'Average of children'), ('weighted', 'Weighted by child weight_pct'), ('none', 'Compute from own KPIs/Tasks only')], default='none', max_length=16)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('target_kind', models.CharField(choices=[('company', 'Company'), ('department', 'Department'), ('employee', 'Employee')], db_index=True, default='company', max_length=12)),
                ('weight_pct', models.PositiveIntegerField(default=100, help_text='0..100 (%) weight')),
                ('progress_pct', models.PositiveIntegerField(db_index=True, default=0, help_text='Aggregated Tasks progress (0..100)')),
                ('score_pct', models.PositiveIntegerField(default=0, help_text='Aggregated KPI score (0..100)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objectives', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent objective in the hierarchy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='performance.objective')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_objectives', to='hr.employee')),
                ('scoring_policy', models.ForeignKey(blank=True, help_text='Override scoring policy for this objective. If empty, use ObjectiveType or Company default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='performance.employeeobjectivescoringpolicy')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_objectives', to='hr.department')),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_objectives', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_objective',
                'permissions': [('close_objective', 'Can close/archive objective'), ('manage_objective_participants', 'Can manage objective participants'), ('manage_objective_kpis', 'Can manage objective KPIs'), ('manage_objective_tasks', 'Can manage objective tasks')],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.AddField(
            model_name='kpi',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='performance.objective'),
        ),
        migrations.AddField(
            model_name='evaluationparameter',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_params', to='performance.objective'),
        ),
        migrations.CreateModel(
            name='EmployeeObjectiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('contribution_pct', models.PositiveIntegerField(default=0)),
                ('tasks_progress_pct', models.PositiveIntegerField(default=0)),
                ('kpi_score_pct', models.PositiveIntegerField(default=0)),
                ('final_score_pct', models.PositiveIntegerField(default=0)),
                ('timeliness_pct', models.PositiveIntegerField(default=100, help_text='On-time completion ratio for this objective (0..100).')),
                ('efficiency_pct', models.PositiveIntegerField(default=100, help_text='Time efficiency score based on estimated vs actual minutes (0..100).')),
                ('quality_pct', models.PositiveIntegerField(default=100, help_text='Average quality score of tasks within this objective (0..100).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_scores', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_scores', to='performance.objective')),
            ],
            options={
                'db_table': 'perf_employee_objective_score',
            },
        ),
        migrations.CreateModel(
            name='ObjectiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_objective_category',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category (Strategic, Operational, Development, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='performance.objectivecategory'),
        ),
        migrations.CreateModel(
            name='ObjectiveDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('include_children', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_assignments', to='hr.department')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_assignments', to='performance.objective')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_objective_dept_assignment',
                'permissions': [('manage_department_assignments', 'Can manage department assignments')],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveEmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_assignments', to='hr.employee')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='performance.objective')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_objective_employee_assignment',
                'permissions': [('manage_employee_assignments', 'Can manage employee assignments')],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_participations', to='hr.employee')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='performance.objective')),
            ],
            options={
                'db_table': 'perf_objective_participant',
                'permissions': [('view_objective_participants', 'Can view objective participants')],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Sorting order')),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_objective_status',
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='status',
            field=models.ForeignKey(help_text='Dynamic status of the objective', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objectives', to='performance.objectivestatus'),
        ),
        migrations.CreateModel(
            name='ObjectiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('default_scoring_policy', models.ForeignKey(blank=True, help_text='Optional default scoring policy for all Objectives of this type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective_type_defaults', to='performance.employeeobjectivescoringpolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_objective_type',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='objective_type',
            field=models.ForeignKey(blank=True, help_text='Type of this objective (Quality, Productivity, Operations, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='performance.objectivetype'),
        ),
        migrations.CreateModel(
            name='PerformanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('impact_pct', models.FloatField(default=0.0, help_text='Optional explicit impact override. If set, overrides type.multiplier.')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_exceptions', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_exception',
                'ordering': ['-date_start'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationExceptionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('adjustment_pct', models.FloatField(default=0.0, help_text='Final adjustment added to evaluation final score (can be negative or positive).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_adjustments', to='performance.evaluation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('exception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_adjustments', to='performance.performanceexception')),
            ],
            options={
                'db_table': 'perf_evaluation_exception_adjustment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceExceptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('multiplier', models.FloatField(default=0.0, help_text='Impact multiplier applied to final score or specific parameters.')),
                ('is_positive', models.BooleanField(default=True, help_text='True = beneficial to employee (reduces penalty), False = negative.')),
                ('max_impact_pct', models.PositiveIntegerField(default=100, help_text='Maximum allowed impact from this exception type.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_exception_type',
                'ordering': ['company', 'name'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AddField(
            model_name='performanceexception',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='performance.performanceexceptiontype'),
        ),
        migrations.CreateModel(
            name='QualityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('impact_score_pct', models.PositiveIntegerField(default=100, help_text='0..100: higher means better handling, lower means worse')),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_incidents', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_quality_incident',
                'ordering': ['-date'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_kind', models.CharField(choices=[('planned', 'Planned Objective Task'), ('temporary', 'Temporary / Ad-hoc Task'), ('bau', 'BAU / Daily Operations Task')], db_index=True, default='planned', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('estimated_minutes', models.PositiveIntegerField(default=0, help_text='Estimated effort for this task (minutes).')),
                ('actual_minutes', models.PositiveIntegerField(default=0, help_text='Actual effort spent (minutes). Optional.')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the assignee actually started working on this task.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was actually completed or cancelled.', null=True)),
                ('quality_score_pct', models.PositiveIntegerField(default=0, help_text='Quality score (0–100), can be set manually or by QA process.')),
                ('quality_reviewed_at', models.DateTimeField(blank=True, help_text='When the quality of this task was reviewed.', null=True)),
                ('quality_notes', models.TextField(blank=True, help_text='Optional notes about quality, findings, or corrections.')),
                ('temporary_source_type', models.CharField(blank=True, help_text='Source of temporary task: NMS Incident, CRM Ticket, etc.', max_length=32)),
                ('temporary_source_ref', models.CharField(blank=True, help_text='External reference ID (IncidentID, TicketID, etc.)', max_length=64)),
                ('blocked_reason', models.TextField(blank=True, help_text='Reason for blocked status (waiting for another team, customer, system issue, etc.).')),
                ('blocked_external', models.BooleanField(default=False, help_text='If True, delay is caused by external factors (should not fully penalize the employee).')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=12)),
                ('percent_complete', models.PositiveIntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_tasks', to='hr.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perf_tasks', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='performance.kpi')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='performance.objective')),
                ('quality_reviewer', models.ForeignKey(blank=True, help_text='Who reviewed/validated the quality of this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_performance_tasks', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_task',
                'permissions': [('assign_task', 'Can assign task to employee'), ('update_task_progress', 'Can update task progress')],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.AddIndex(
            model_name='dailyrating',
            index=models.Index(fields=['employee', 'date'], name='perf_daily__employe_6a4aad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrating',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailyratingfactor',
            index=models.Index(fields=['company', 'active'], name='perf_daily__company_ea735d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyratingfactor',
            index=models.Index(fields=['company', 'name'], name='perf_daily__company_423598_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyratingfactor',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='dailyratingitem',
            index=models.Index(fields=['daily_rating', 'factor'], name='perf_daily__daily_r_7e16e2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyratingitem',
            index=models.Index(fields=['score_pct'], name='perf_daily__score_p_99163e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyratingitem',
            unique_together={('daily_rating', 'factor')},
        ),
        migrations.AddIndex(
            model_name='employeeobjectivescoringpolicy',
            index=models.Index(fields=['company', 'active'], name='perf_employ_company_6ebfee_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationparameterresult',
            index=models.Index(fields=['evaluation', 'parameter'], name='perf_evalua_evaluat_385ad3_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationparameterresult',
            constraint=models.CheckConstraint(condition=models.Q(('score_pct__gte', 0), ('score_pct__lte', 100)), name='chk_param_result_score_0_100'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationparameterresult',
            unique_together={('evaluation', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationtemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='evaluationtype',
            index=models.Index(fields=['company', 'active'], name='evaltype_comp_active'),
        ),
        migrations.AddIndex(
            model_name='evaluationtype',
            index=models.Index(fields=['company', 'sequence'], name='evaltype_comp_seq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('company', 'code'), name='perf_evaltype_company_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='evaluationapprovalstep',
            index=models.Index(fields=['company', 'evaluation_type', 'sequence'], name='evalstep_comp_type_seq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationapprovalstep',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('company', 'evaluation_type', 'code'), name='perf_evalstep_company_type_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationapprovalstep',
            constraint=models.CheckConstraint(condition=models.Q(('manager_level__gte', 1)), name='chk_evalstep_manager_level_gte_1'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['company', 'employee', 'date_start', 'date_end'], name='perf_evalua_company_debdd8_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['state', 'date_end'], name='eval_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('date_start__lte', models.F('date_end'))), name='chk_eval_dates'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('employee', 'date_start', 'date_end'), name='uniq_eval_employee_period'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('final_score_pct__gte', 0), ('final_score_pct__lte', 100)), name='chk_eval_final_0_100'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['company', 'objective'], name='perf_kpi_company_202f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['attainment_pct', 'score_pct'], name='perf_kpi_attainm_26971f_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.CheckConstraint(condition=models.Q(('weight_pct__gte', 0), ('weight_pct__lte', 100)), name='chk_kpi_weight_0_100'),
        ),
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.CheckConstraint(condition=models.Q(('attainment_pct__gte', 0), ('attainment_pct__lte', 200)), name='chk_kpi_att_0_200'),
        ),
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.CheckConstraint(condition=models.Q(('score_pct__gte', 0), ('score_pct__lte', 100)), name='chk_kpi_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='evaluationparameter',
            constraint=models.CheckConstraint(condition=models.Q(('weight_pct__gte', 0), ('weight_pct__lte', 100)), name='chk_param_weight_0_100_v2'),
        ),
        migrations.AddConstraint(
            model_name='evaluationparameter',
            constraint=models.CheckConstraint(condition=models.Q(('min_score_pct__gte', 0), ('min_score_pct__lte', 100)), name='chk_param_min_0_100'),
        ),
        migrations.AddConstraint(
            model_name='evaluationparameter',
            constraint=models.CheckConstraint(condition=models.Q(('max_score_pct__gte', 0), ('max_score_pct__lte', 100)), name='chk_param_max_0_100'),
        ),
        migrations.AddConstraint(
            model_name='evaluationparameter',
            constraint=models.CheckConstraint(condition=models.Q(('min_score_pct__lte', models.F('max_score_pct'))), name='chk_param_min_le_max'),
        ),
        migrations.AddConstraint(
            model_name='evaluationparameter',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('template', 'code'), name='perf_param_template_code_uniq_v2'),
        ),
        migrations.AddIndex(
            model_name='employeeobjectivescore',
            index=models.Index(fields=['objective', 'employee'], name='perf_employ_objecti_a6ee3f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeobjectivescore',
            index=models.Index(fields=['final_score_pct'], name='perf_employ_final_s_1b2cc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('contribution_pct__gte', 0), ('contribution_pct__lte', 100)), name='chk_eos_contribution_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('tasks_progress_pct__gte', 0), ('tasks_progress_pct__lte', 100)), name='chk_eos_tasks_progress_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('kpi_score_pct__gte', 0), ('kpi_score_pct__lte', 100)), name='chk_eos_kpi_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('final_score_pct__gte', 0), ('final_score_pct__lte', 100)), name='chk_eos_final_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('timeliness_pct__gte', 0), ('timeliness_pct__lte', 100)), name='chk_eos_timeliness_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('efficiency_pct__gte', 0), ('efficiency_pct__lte', 100)), name='chk_eos_efficiency_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('quality_pct__gte', 0), ('quality_pct__lte', 100)), name='chk_eos_quality_0_100'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeobjectivescore',
            unique_together={('objective', 'employee')},
        ),
        migrations.AddIndex(
            model_name='objectivecategory',
            index=models.Index(fields=['active'], name='perf_object_active_0d80cc_idx'),
        ),
        migrations.AddIndex(
            model_name='objectivecategory',
            index=models.Index(fields=['code'], name='perf_object_code_9bc5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='objectivedepartmentassignment',
            index=models.Index(fields=['objective', 'department'], name='perf_object_objecti_137b6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectivedepartmentassignment',
            constraint=models.UniqueConstraint(fields=('objective', 'department'), name='perf_obj_dept_uniq'),
        ),
        migrations.AddIndex(
            model_name='objectiveemployeeassignment',
            index=models.Index(fields=['objective', 'employee'], name='perf_object_objecti_e95587_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectiveemployeeassignment',
            constraint=models.UniqueConstraint(fields=('objective', 'employee'), name='perf_obj_emp_uniq'),
        ),
        migrations.AddIndex(
            model_name='objectiveparticipant',
            index=models.Index(fields=['employee', 'objective'], name='perf_object_employe_303d9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectiveparticipant',
            constraint=models.UniqueConstraint(fields=('objective', 'employee'), name='perf_obj_participant_uniq'),
        ),
        migrations.AddIndex(
            model_name='objectivestatus',
            index=models.Index(fields=['active'], name='perf_object_active_081877_idx'),
        ),
        migrations.AddIndex(
            model_name='objectivestatus',
            index=models.Index(fields=['code'], name='perf_object_code_6d502d_idx'),
        ),
        migrations.AddIndex(
            model_name='objectivetype',
            index=models.Index(fields=['active'], name='perf_object_active_5f5d79_idx'),
        ),
        migrations.AddIndex(
            model_name='objectivetype',
            index=models.Index(fields=['code'], name='perf_object_code_6f9169_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['company', 'status'], name='perf_object_company_ad3959_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['company', 'objective_type'], name='perf_object_company_12a1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['company', 'category'], name='perf_object_company_f5c538_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['date_start', 'date_end'], name='perf_object_date_st_3afab9_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['parent'], name='perf_object_parent__5830b8_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['hierarchy_level'], name='perf_object_hierarc_fab0cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.CheckConstraint(condition=models.Q(('weight_pct__gte', 0), ('weight_pct__lte', 100)), name='chk_objective_weight_0_100'),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.CheckConstraint(condition=models.Q(('progress_pct__gte', 0), ('progress_pct__lte', 100)), name='chk_objective_progress_0_100'),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.CheckConstraint(condition=models.Q(('score_pct__gte', 0), ('score_pct__lte', 100)), name='chk_objective_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.CheckConstraint(condition=models.Q(('date_end__isnull', True), ('date_start__lte', models.F('date_end')), _connector='OR'), name='chk_objective_dates'),
        ),
        migrations.AlterUniqueTogether(
            name='performanceexceptiontype',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='performanceexception',
            index=models.Index(fields=['employee', 'date_start'], name='perf_except_employe_ddbc77_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceexception',
            index=models.Index(fields=['type'], name='perf_except_type_id_eccdc8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'objective', 'status'], name='perf_task_company_9f1537_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='perf_task_due_dat_1b2048_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('percent_complete__gte', 0), ('percent_complete__lte', 100)), name='chk_task_percent_0_100'),
        ),
    ]
