# Generated by Django 5.2.7 on 2025-11-29 21:41

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0005_alter_department_managers'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICalculationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('formula_type', models.CharField(choices=[('ratio', 'current / target'), ('inverse_ratio', 'target / current'), ('progressive', 'progressive scaling upto 200%'), ('manual', 'Manual score (entered directly)')], default='ratio', max_length=32)),
                ('green_threshold_pct', models.PositiveIntegerField(default=90)),
                ('yellow_threshold_pct', models.PositiveIntegerField(default=70)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'perf_kpi_calc_method',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='KPICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'perf_kpi_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='KPIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'perf_kpi_type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'perf_task_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'perf_task_dependency',
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgressPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('use_subtasks', models.BooleanField(default=False)),
                ('use_time_ratio', models.BooleanField(default=False)),
                ('use_status_mapping', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perf_task_progress_policy',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaskRecurringDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('schedule_kind', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('custom', 'Custom Period')], db_index=True, default='monthly', max_length=16)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'perf_task_recurring_definition',
                'ordering': ('company', 'name'),
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskSLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('on_time_pct', models.PositiveIntegerField(default=100)),
                ('mild_delay_pct', models.PositiveIntegerField(default=80)),
                ('severe_delay_pct', models.PositiveIntegerField(default=50)),
                ('allow_blocked_external_no_penalty', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perf_task_sla_policy',
                'ordering': ('company', 'name'),
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('is_closed', models.BooleanField(default=False, help_text='Does this status close the task?')),
                ('is_blocking', models.BooleanField(default=False, help_text='Is this a blocking state?')),
            ],
            options={
                'db_table': 'perf_task_status',
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'perf_task_type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'perf_task_watcher',
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='perf_task_company_9f1537_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_kind',
        ),
        migrations.AddField(
            model_name='evaluationtemplate',
            name='evaluation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='performance.evaluationtype'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('external', 'External System')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='kpi',
            name='external_source_ref',
            field=models.CharField(blank=True, help_text='Reference if KPI data comes from external system.', max_length=128),
        ),
        migrations.AddField(
            model_name='kpi',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kpi',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Employee responsible for updating KPI data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_kpis', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='blocking_tasks', to='performance.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='efficiency_pct',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='task',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='performance.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_pct',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='task',
            name='timeliness_pct',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='blocked_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='blocked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='quality_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='quality_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='quality_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_performance_tasks', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quality_score_pct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='temporary_source_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='temporary_source_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='kpicalculationmethod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpicalculationmethod',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='calculation_method',
            field=models.ForeignKey(blank=True, help_text='Dynamic calculation rule for KPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='performance.kpicalculationmethod'),
        ),
        migrations.AddField(
            model_name='kpicategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpicategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='performance.kpicategory'),
        ),
        migrations.AddField(
            model_name='kpitype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpitype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kpi_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='performance.kpitype'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='performance.taskcategory'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_dependencies', to='base.company'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocking', to='performance.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='performance.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskprogresspolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskprogresspolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='performance.taskprogresspolicy'),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_task_definitions', to='base.company'),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_definitions_department', to='hr.department'),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='excluded_employees',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_recurring_tasks', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_task_definitions', to='performance.objective'),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='progress_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_definitions', to='performance.taskprogresspolicy'),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='task_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_definitions', to='performance.taskcategory'),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_definitions_team', to='hr.department'),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskslapolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company'),
        ),
        migrations.AddField(
            model_name='taskslapolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskslapolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_definitions', to='performance.taskslapolicy'),
        ),
        migrations.AddField(
            model_name='task',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='performance.taskslapolicy'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='performance.taskstatus'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrecurringdefinition',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_definitions', to='performance.tasktype'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='performance.tasktype'),
        ),
        migrations.AddField(
            model_name='taskwatcher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_watchers', to='base.company'),
        ),
        migrations.AddField(
            model_name='taskwatcher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskwatcher',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_watcher_links', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='taskwatcher',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_links', to='performance.task'),
        ),
        migrations.AddField(
            model_name='taskwatcher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_tasks', through='performance.TaskWatcher', to='hr.employee'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'objective'], name='perf_task_company_28d4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='perf_task_status__2be496_idx'),
        ),
        migrations.AddIndex(
            model_name='kpicategory',
            index=models.Index(fields=['active'], name='perf_kpi_ca_active_c0d2df_idx'),
        ),
        migrations.AddIndex(
            model_name='kpicategory',
            index=models.Index(fields=['code'], name='perf_kpi_ca_code_cd0b22_idx'),
        ),
        migrations.AddIndex(
            model_name='kpitype',
            index=models.Index(fields=['active'], name='perf_kpi_ty_active_3c1ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='kpitype',
            index=models.Index(fields=['code'], name='perf_kpi_ty_code_fb1105_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcategory',
            index=models.Index(fields=['active', 'code'], name='perf_task_c_active_aaa405_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['task', 'depends_on'], name='perf_task_d_task_id_9c1342_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('task', 'depends_on')},
        ),
        migrations.AddIndex(
            model_name='taskslapolicy',
            index=models.Index(fields=['company', 'active'], name='perf_task_s_company_5fe735_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['active', 'code'], name='perf_task_s_active_e207c3_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktype',
            index=models.Index(fields=['active', 'code'], name='perf_task_t_active_8a1c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecurringdefinition',
            index=models.Index(fields=['company', 'active'], name='perf_task_r_company_483ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecurringdefinition',
            index=models.Index(fields=['schedule_kind'], name='perf_task_r_schedul_c477aa_idx'),
        ),
        migrations.AddIndex(
            model_name='taskwatcher',
            index=models.Index(fields=['task', 'employee'], name='perf_task_w_task_id_33915e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskwatcher',
            unique_together={('task', 'employee')},
        ),
    ]
