# Generated by Django 5.2.7 on 2025-12-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_kpicalculationmethod_kpicategory_kpitype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtemplate',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='إذا كان القالب مستخدماً في تقييمات فعلية يتم تجميده، ولا يُسمح بتعديل معاملاته أو هيكله الأساسي للحفاظ على عدالة التقييمات التاريخية.'),
        ),
        migrations.AddField(
            model_name='evaluationtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='رقم إصدار القالب لتمييز النسخ المختلفة عبر السنوات/الدورات.'),
        ),
    ]
