# Generated by Django 5.2.7 on 2025-11-02 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_partner_partner_comp_iscomp_name_idx'),
        ('hr', '0001_initial'),
        ('performance', '0002_alter_evaluationtemplate_managers_alter_kpi_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_objectives', to='hr.department'),
        ),
        migrations.AddField(
            model_name='objective',
            name='target_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_objectives', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='objective',
            name='target_kind',
            field=models.CharField(choices=[('company', 'Company'), ('department', 'Department'), ('employee', 'Employee')], db_index=True, default='company', max_length=12),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['company', 'target_kind'], name='perf_object_company_4f115e_idx'),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_kind', 'company'), ('target_department__isnull', True), ('target_employee__isnull', True)), models.Q(('target_kind', 'department'), ('target_department__isnull', False), ('target_employee__isnull', True)), models.Q(('target_kind', 'employee'), ('target_employee__isnull', False), ('target_department__isnull', True)), _connector='OR'), name='chk_objective_target_consistency'),
        ),
    ]
