# Generated by Django 5.2.7 on 2025-11-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_objective_target_department_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='objective',
            name='chk_objective_target_consistency',
        ),
    ]
