# Generated by Django 5.2.7 on 2025-11-02 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_remove_objective_chk_objective_target_consistency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluationparameter',
            name='chk_param_weight_0_100',
        ),
        migrations.RemoveConstraint(
            model_name='evaluationparameter',
            name='perf_param_template_code_uniq',
        ),
        migrations.AddConstraint(
            model_name='evaluationparameter',
            constraint=models.CheckConstraint(condition=models.Q(('weight_pct__gte', 0), ('weight_pct__lte', 100)), name='chk_param_weight_0_100_v2'),
        ),
        migrations.AddConstraint(
            model_name='evaluationparameter',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('template', 'code'), name='perf_param_template_code_uniq_v2'),
        ),
    ]
