# Generated by Django 5.2.7 on 2025-11-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_alter_evaluation_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='unit',
            field=models.CharField(choices=[('#', 'Count'), ('%', 'Percent'), ('IQD', 'IQD'), ('USD', 'USD'), ('hrs', 'Hours'), ('min', 'Minutes'), ('custom', 'Custom')], default='#', max_length=10),
        ),
    ]
