# Generated by Django 5.2.7 on 2025-11-24 18:11

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0005_alter_department_managers'),
        ('performance', '0008_alter_evaluation_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True, default=10)),
                ('frequency_label', models.CharField(blank=True, help_text='وصف حر للتكرار (مثلاً: Monthly / Quarterly / Project-based).', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_evaluation_type',
                'ordering': ('company', 'sequence', 'name'),
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True, default=10, help_text='ترتيب الخطوة داخل سير الموافقات (كلما قل الرقم كانت الخطوة أبكر).')),
                ('approver_kind', models.CharField(choices=[('direct_manager', 'Direct Manager'), ('department_manager', 'Department Manager'), ('manager_chain', 'Manager Chain (Level)'), ('employee', 'Specific Employee'), ('group', 'Specific Group/Role')], default='direct_manager', max_length=32)),
                ('manager_level', models.PositiveSmallIntegerField(default=1, help_text='يُستخدم فقط عند اختيار MANAGER_CHAIN لتحديد مستوى المدير في السلسلة.')),
                ('description', models.TextField(blank=True)),
                ('approver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps_as_specific_approver', to='hr.employee')),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_approval_steps', to='auth.group')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='performance.evaluationtype')),
            ],
            options={
                'db_table': 'perf_evaluation_approval_step',
                'ordering': ('company', 'evaluation_type', 'sequence', 'id'),
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='evaluationtype',
            index=models.Index(fields=['company', 'active'], name='evaltype_comp_active'),
        ),
        migrations.AddIndex(
            model_name='evaluationtype',
            index=models.Index(fields=['company', 'sequence'], name='evaltype_comp_seq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('company', 'code'), name='perf_evaltype_company_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='evaluationapprovalstep',
            index=models.Index(fields=['company', 'evaluation_type', 'sequence'], name='evalstep_comp_type_seq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationapprovalstep',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('company', 'evaluation_type', 'code'), name='perf_evalstep_company_type_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationapprovalstep',
            constraint=models.CheckConstraint(condition=models.Q(('manager_level__gte', 1)), name='chk_evalstep_manager_level_gte_1'),
        ),
    ]
