# Generated by Django 5.2.7 on 2025-11-25 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0005_alter_department_managers'),
        ('performance', '0011_rename_perf_eval_state_idx_eval_state_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='hierarchy_level',
            field=models.PositiveIntegerField(default=1, help_text='1 = Company, 2 = Division, 3 = Department, 4 = Section, 5 = Team, 6 = Employee'),
        ),
        migrations.AddField(
            model_name='objective',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent objective for hierarchical planning.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='performance.objective'),
        ),
        migrations.AddField(
            model_name='objective',
            name='rollup_strategy',
            field=models.CharField(choices=[('average', 'Average of children'), ('weighted', 'Weighted by child weight_pct'), ('none', 'No rollup (objective computed from own KPIs/Tasks only)')], default='none', max_length=16),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['parent'], name='perf_object_parent__5830b8_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['hierarchy_level'], name='perf_object_hierarc_fab0cd_idx'),
        ),
    ]
