# Generated by Django 5.2.7 on 2025-11-25 19:04

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0005_alter_department_managers'),
        ('performance', '0012_objective_hierarchy_level_objective_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationparameter',
            name='source_kind',
            field=models.CharField(choices=[('objective_score', 'Objective Score (score_pct)'), ('objective_progress', 'Objective Progress (progress_pct)'), ('kpi_score', 'KPI Score (score_pct)'), ('tasks_progress', 'Tasks Progress (avg % complete)'), ('external_metric', 'External Metric (model/field/filter)'), ('manual', 'Manual Entry (default)'), ('daily_rating', 'Daily Rating (avg overall score)')], default='manual', max_length=32),
        ),
        migrations.CreateModel(
            name='DailyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('overall_score_pct', models.PositiveIntegerField(default=0, help_text='Aggregated score of rating items (0..100).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ratings', to='hr.employee')),
                ('rated_by', models.ForeignKey(blank=True, help_text='Usually the direct manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_daily_ratings', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_daily_rating',
                'ordering': ['-date', 'employee'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyRatingFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight_pct', models.PositiveIntegerField(default=100, help_text='Weight inside daily rating aggregation (0..100).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_daily_rating_factor',
                'ordering': ['company', 'name'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyRatingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('score_pct', models.PositiveIntegerField(default=0, help_text='0..100')),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('daily_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='performance.dailyrating')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_items', to='performance.dailyratingfactor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_daily_rating_item',
            },
        ),
        migrations.CreateModel(
            name='EmployeeObjectiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('contribution_pct', models.PositiveIntegerField(default=0)),
                ('tasks_progress_pct', models.PositiveIntegerField(default=0)),
                ('kpi_score_pct', models.PositiveIntegerField(default=0)),
                ('final_score_pct', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_scores', to='hr.employee')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_scores', to='performance.objective')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_employee_objective_score',
            },
        ),
        migrations.AddIndex(
            model_name='dailyrating',
            index=models.Index(fields=['employee', 'date'], name='perf_daily__employe_6a4aad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrating',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailyratingfactor',
            index=models.Index(fields=['company', 'active'], name='perf_daily__company_ea735d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyratingfactor',
            index=models.Index(fields=['company', 'name'], name='perf_daily__company_423598_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyratingfactor',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='dailyratingitem',
            index=models.Index(fields=['daily_rating', 'factor'], name='perf_daily__daily_r_7e16e2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyratingitem',
            index=models.Index(fields=['score_pct'], name='perf_daily__score_p_99163e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyratingitem',
            unique_together={('daily_rating', 'factor')},
        ),
        migrations.AddIndex(
            model_name='employeeobjectivescore',
            index=models.Index(fields=['objective', 'employee'], name='perf_employ_objecti_a6ee3f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeobjectivescore',
            index=models.Index(fields=['final_score_pct'], name='perf_employ_final_s_1b2cc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeobjectivescore',
            unique_together={('objective', 'employee')},
        ),
    ]
