# Generated by Django 5.2.7 on 2025-11-28 21:41

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0005_alter_department_managers'),
        ('performance', '0014_evaluation_calibrated_score_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeObjectiveScoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('tasks_weight_pct', models.PositiveIntegerField(default=30, help_text='Weight for Tasks Progress (0..100).')),
                ('kpi_weight_pct', models.PositiveIntegerField(default=30, help_text='Weight for KPI Score (0..100).')),
                ('timeliness_weight_pct', models.PositiveIntegerField(default=15, help_text='Weight for Timeliness (0..100).')),
                ('efficiency_weight_pct', models.PositiveIntegerField(default=10, help_text='Weight for Time Efficiency (0..100).')),
                ('quality_weight_pct', models.PositiveIntegerField(default=15, help_text='Weight for Tasks Quality (0..100).')),
            ],
            options={
                'db_table': 'perf_employee_objective_scoring_policy',
                'ordering': ('company', 'name'),
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AddField(
            model_name='employeeobjectivescore',
            name='efficiency_pct',
            field=models.PositiveIntegerField(default=100, help_text='Time efficiency score based on estimated vs actual minutes (0..100).'),
        ),
        migrations.AddField(
            model_name='employeeobjectivescore',
            name='quality_pct',
            field=models.PositiveIntegerField(default=100, help_text='Average quality score of tasks within this objective (0..100).'),
        ),
        migrations.AddField(
            model_name='employeeobjectivescore',
            name='timeliness_pct',
            field=models.PositiveIntegerField(default=100, help_text='On-time completion ratio for this objective (0..100).'),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_external',
            field=models.BooleanField(default=False, help_text='If True, delay is caused by external factors (should not fully penalize the employee).'),
        ),
        migrations.AddField(
            model_name='task',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Reason for blocked status (waiting for another team, customer, system issue, etc.).'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the task was actually completed or cancelled.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Optional notes about quality, findings, or corrections.'),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the quality of this task was reviewed.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_reviewer',
            field=models.ForeignKey(blank=True, help_text='Who reviewed/validated the quality of this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_performance_tasks', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the assignee actually started working on this task.', null=True),
        ),
        migrations.AlterField(
            model_name='evaluationparameter',
            name='source_kind',
            field=models.CharField(choices=[('objective_score', 'Objective Score (score_pct)'), ('objective_progress', 'Objective Progress (progress_pct)'), ('kpi_score', 'KPI Score (score_pct)'), ('tasks_progress', 'Tasks Progress (avg % complete)'), ('external_metric', 'External Metric (model/field/filter)'), ('manual', 'Manual Entry (default)'), ('daily_rating', 'Daily Rating (avg overall score)'), ('temp_tasks_load', 'Temporary Tasks Load Index'), ('temp_tasks_score', 'Temporary Tasks Performance Score'), ('employee_objective_score', 'Employee Objective Contribution Score'), ('employee_objective_timeliness', 'Employee Objective Timeliness (Tasks Due/Done)'), ('employee_objective_efficiency', 'Employee Objective Time Efficiency'), ('employee_objective_quality', 'Employee Objective Tasks Quality'), ('quality_score', 'Quality / Mistakes / Complaints Score'), ('feedback_score', '360° Feedback (Self/Manager/Peers)')], default='manual', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('contribution_pct__gte', 0), ('contribution_pct__lte', 100)), name='chk_eos_contribution_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('tasks_progress_pct__gte', 0), ('tasks_progress_pct__lte', 100)), name='chk_eos_tasks_progress_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('kpi_score_pct__gte', 0), ('kpi_score_pct__lte', 100)), name='chk_eos_kpi_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('final_score_pct__gte', 0), ('final_score_pct__lte', 100)), name='chk_eos_final_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('timeliness_pct__gte', 0), ('timeliness_pct__lte', 100)), name='chk_eos_timeliness_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('efficiency_pct__gte', 0), ('efficiency_pct__lte', 100)), name='chk_eos_efficiency_0_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeobjectivescore',
            constraint=models.CheckConstraint(condition=models.Q(('quality_pct__gte', 0), ('quality_pct__lte', 100)), name='chk_eos_quality_0_100'),
        ),
        migrations.AddField(
            model_name='employeeobjectivescoringpolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='base.company'),
        ),
        migrations.AddField(
            model_name='employeeobjectivescoringpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeobjectivescoringpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeeobjectivescoringpolicy',
            index=models.Index(fields=['company', 'active'], name='perf_employ_company_6ebfee_idx'),
        ),
    ]
