# Generated by Django 5.2.7 on 2025-11-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0015_employeeobjectivescoringpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='scoring_policy',
            field=models.ForeignKey(blank=True, help_text='Optional scoring policy for this objective. If empty, the company default policy will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='performance.employeeobjectivescoringpolicy'),
        ),
    ]
