# Generated by Django 5.2.7 on 2025-10-31 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='XField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('char', 'Char'), ('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('choice', 'Choice (single)'), ('multi_choice', 'Multi-Choice')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xfields', to='base.company')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xfields', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'xf_field',
            },
        ),
        migrations.CreateModel(
            name='XFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='xfields.xfield')),
            ],
            options={
                'db_table': 'xf_field_option',
                'ordering': ['field', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='XValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('char_value', models.CharField(blank=True, max_length=500, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('int_value', models.BigIntegerField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xf_values', to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='xfields.xfield')),
            ],
            options={
                'db_table': 'xf_value',
            },
        ),
        migrations.AddIndex(
            model_name='xfield',
            index=models.Index(fields=['model', 'code'], name='xf_field_model_i_b1630a_idx'),
        ),
        migrations.AddIndex(
            model_name='xfield',
            index=models.Index(fields=['company'], name='xf_field_company_782b83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xfield',
            unique_together={('model', 'company', 'code')},
        ),
        migrations.AddConstraint(
            model_name='xfieldoption',
            constraint=models.CheckConstraint(condition=models.Q(('value', ''), _negated=True), name='xf_option_value_not_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='xfieldoption',
            unique_together={('field', 'value')},
        ),
        migrations.AddIndex(
            model_name='xvalue',
            index=models.Index(fields=['content_type', 'object_id'], name='xf_value_content_cc4df7_idx'),
        ),
        migrations.AddIndex(
            model_name='xvalue',
            index=models.Index(fields=['field', 'content_type', 'object_id'], name='xf_value_field_i_59af4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='xvalue',
            constraint=models.UniqueConstraint(fields=('field', 'content_type', 'object_id'), name='xf_one_value_per_field_per_record'),
        ),
    ]
