# Generated by Django 5.2.7 on 2025-11-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xfields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xvalue',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
