# Generated by Django 5.2.7 on 2025-12-19 15:17

import base.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0007_department_uniq_department_per_company_parent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('is_quantity', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_input_types', to='base.company')),
            ],
            options={
                'db_table': 'payroll_input_type',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='base.company')),
            ],
            options={
                'db_table': 'payroll_period',
                'ordering': ['-year', '-month'],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.CreateModel(
            name='PayrollStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('use_worked_day_lines', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_structures', to='base.company')),
            ],
            options={
                'db_table': 'payroll_structure',
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_wage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_wage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('paid', 'Paid'), ('cancel', 'Cancelled')], default='draft', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='base.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.job')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollperiod')),
                ('struct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollstructure')),
            ],
            options={
                'db_table': 'payroll_payslip',
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.CreateModel(
            name='PayslipInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_inputs', to='base.company')),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_inputs', to='payroll.inputtype')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='payroll.payslip')),
            ],
            options={
                'db_table': 'payroll_payslip_input',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_rule_params', to='base.company')),
            ],
            options={
                'db_table': 'payroll_rule_parameter',
            },
        ),
        migrations.CreateModel(
            name='SalaryRuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('sequence', models.PositiveSmallIntegerField(default=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_rule_categories', to='base.company')),
            ],
            options={
                'db_table': 'payroll_rule_category',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=100)),
                ('condition_select', models.CharField(choices=[('always', 'Always'), ('python', 'Python Expression')], default='always', max_length=10)),
                ('condition_python', models.TextField(blank=True, default='result = True')),
                ('amount_python', models.TextField(default='amount = BASIC\nquantity = 1\nrate = 100\ntotal = amount')),
                ('input_usage_employee', models.BooleanField(default=False)),
                ('unique_code_per_struct', models.BooleanField(default=True)),
                ('struct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll.payrollstructure')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='payroll.salaryrulecategory')),
            ],
            options={
                'db_table': 'payroll_salary_rule',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField(default=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='base.company')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='payroll.salaryrulecategory')),
            ],
            options={
                'db_table': 'payroll_payslip_line',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='base.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='hr.employee')),
            ],
            options={
                'db_table': 'payroll_employee_salary',
                'ordering': ['-date_start'],
                'indexes': [models.Index(fields=['employee', 'company', 'date_start', 'date_end'], name='payroll_emp_employe_e5e25b_idx')],
            },
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],

        ),
        migrations.AddIndex(
            model_name='inputtype',
            index=models.Index(fields=['company', 'code'], name='payroll_inp_company_bb6f8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inputtype',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['company', 'year', 'month', 'state'], name='payroll_per_company_8909be_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('date_from__lte', models.F('date_to'))), name='chk_payroll_period_dates'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='chk_payroll_period_month_1_12'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('company', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='payrollstructure',
            index=models.Index(fields=['company', 'code'], name='payroll_str_company_7ddb0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollstructure',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'period', 'employee', 'state'], name='ps_c_p_e_s_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'period', 'department'], name='ps_c_p_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'period'], name='ps_emp_per_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['state'], name='ps_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('company', 'employee', 'period'), name='uniq_ps_co_emp_per'),
        ),
        migrations.AddIndex(
            model_name='payslipinput',
            index=models.Index(fields=['payslip', 'input_type'], name='payroll_pay_payslip_b24e96_idx'),
        ),
        migrations.AddIndex(
            model_name='payslipinput',
            index=models.Index(fields=['payslip', 'sequence'], name='payroll_pay_payslip_92538d_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleparameter',
            index=models.Index(fields=['company', 'code'], name='payroll_rul_company_be243e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ruleparameter',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryrulecategory',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='salaryrule',
            index=models.Index(fields=['struct', 'sequence'], name='payroll_sal_struct__d1d334_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrule',
            index=models.Index(fields=['struct', 'code'], name='payroll_sal_struct__a23fa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrule',
            unique_together={('struct', 'code')},
        ),
        migrations.AddIndex(
            model_name='payslipline',
            index=models.Index(fields=['payslip', 'code', 'category'], name='payroll_pay_payslip_61aa19_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__lt', 0), _negated=True), name='psl_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('rate__lt', 0), _negated=True), name='psl_rate_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__lt', 0), _negated=True), name='psl_qty_nonneg'),
        ),
    ]
