# Generated by Django 5.2.7 on 2025-10-23 15:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='base.company')),
            ],
            options={
                'db_table': 'payroll_period',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kind', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_adjustments', to='base.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_adjustments', to='hr.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_monthly_adjustment',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='base.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.job')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_payslip',
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('basic', 'Basic'), ('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
            ],
            options={
                'db_table': 'payroll_payslip_line',
            },
        ),
        migrations.CreateModel(
            name='RecurringComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kind', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_components', to='base.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_components', to='hr.employee')),
            ],
            options={
                'db_table': 'payroll_recurring_component',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='base.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='hr.employee')),
            ],
            options={
                'db_table': 'payroll_employee_salary',
                'ordering': ['-date_start'],
                'indexes': [models.Index(fields=['employee', 'company', 'date_start', 'date_end'], name='payroll_emp_employe_e5e25b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['company', 'year', 'month', 'state'], name='payroll_per_company_8909be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('company', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='monthlyadjustment',
            index=models.Index(fields=['employee', 'company', 'period', 'kind'], name='payroll_mon_employe_9d129a_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'period', 'employee', 'state'], name='payroll_pay_company_74504a_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'period', 'department'], name='payroll_pay_company_def2dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'period')},
        ),
        migrations.AddIndex(
            model_name='payslipline',
            index=models.Index(fields=['payslip', 'kind'], name='payroll_pay_payslip_3a148b_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringcomponent',
            index=models.Index(fields=['employee', 'company', 'kind', 'date_start', 'date_end', 'active'], name='payroll_rec_employe_4e641b_idx'),
        ),
    ]
