# Generated by Django 5.2.7 on 2025-11-05 19:00

import base.acl
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeesalary',
            managers=[
                ('objects', base.acl.ACLManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payrollperiod',
            managers=[
                ('objects', base.acl.ACLManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payslip',
            managers=[
                ('objects', base.acl.ACLManager()),
            ],
        ),
    ]
