# Generated by Django 5.2.7 on 2025-11-01 21:22

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeesalary',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='monthlyadjustment',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payrollperiod',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payslip',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recurringcomponent',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
    ]
