# Generated by Django 5.2.7 on 2026-01-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeesalary',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='payrollperiod',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='payrollstructure',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='payslip',
            managers=[
            ],
        ),
    ]
