# Generated by Django 5.2.7 on 2025-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='objectacl',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('content_type', 'object_id', 'user'), name='acl_unique_ct_obj_user'),
        ),
        migrations.AddConstraint(
            model_name='objectacl',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('content_type', 'object_id', 'group'), name='acl_unique_ct_obj_group'),
        ),
    ]
