# Generated by Django 5.2.7 on 2025-10-05 18:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partner_name_400a92_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_email_7bbb4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_active_e4b864_idx',
        ),
        migrations.RenameIndex(
            model_name='partner',
            new_name='partner_disp_idx',
            old_name='partner_display_d7424d_idx',
        ),
        migrations.RenameIndex(
            model_name='partner',
            new_name='partner_ctype_idx',
            old_name='partner_company_f4018f_idx',
        ),
        migrations.RenameIndex(
            model_name='partner',
            new_name='partner_type_idx',
            old_name='partner_type_b63f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='partner',
            new_name='partner_active_idx',
            old_name='partner_active_601d37_idx',
        ),
        migrations.RenameIndex(
            model_name='partner',
            new_name='partner_flat_parent_mix_idx',
            old_name='partner_parent__6a4bcd_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_active_joined_idx',
            old_name='user_is_acti_0fb501_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_username_idx',
            old_name='user_usernam_b79065_idx',
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='partner_name_ci_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['parent'], name='partner_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['company'], name='partner_company_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='user_email_ci_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company'], name='user_company_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='user_last_login_idx'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='partner_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='user_email_not_empty'),
        ),
    ]
