# Generated by Django 5.2.7 on 2025-11-01 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company_type', 'company'), ('is_company', True)), models.Q(('company_type', 'person'), ('is_company', False)), _connector='OR'), name='partner_company_type_matches_flag'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('is_company', True), models.Q(('is_company', False), ('type', 'contact')), _connector='OR'), name='partner_person_must_be_contact_type'),
        ),
    ]
