# Generated by Django 5.2.6 on 2025-09-26 21:31

import base.models.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_company_partner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('objects', base.models.managers.CompanyScopeManager()),
            ],
        ),
    ]
