# Generated by Django 5.2.7 on 2025-11-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_company_created_by_company_updated_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['company', 'is_company', 'name'], name='partner_comp_iscomp_name_idx'),
        ),
    ]
