# Generated by Django 5.2.7 on 2025-10-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0002_objectacl_acl_unique_ct_obj_user_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='objectacl',
            name='acl_has_perm',
        ),
        migrations.AddField(
            model_name='objectacl',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='can_assign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='can_attach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='can_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='can_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='can_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='can_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectacl',
            name='extra_perms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='objectacl',
            constraint=models.CheckConstraint(condition=models.Q(('can_view', True), ('can_change', True), ('can_delete', True), ('can_share', True), ('can_approve', True), ('can_assign', True), ('can_comment', True), ('can_export', True), ('can_rate', True), ('can_attach', True), models.Q(('extra_perms', []), _negated=True), _connector='OR'), name='acl_has_any_perm'),
        ),
    ]
