# Generated by Django 5.2.7 on 2025-11-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_partner_partner_comp_iscomp_name_idx'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                # Manager افتراضي فقط (بدون ACL)
                ('objects', models.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usersettings',
            managers=[
                # Manager افتراضي فقط (بدون ACL)
                ('objects', models.Manager()),
            ],
        ),
    ]
