# Generated by Django 5.2.7 on 2025-11-05 17:47

import base.acl
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_partner_partner_comp_iscomp_name_idx'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', base.acl.ACLManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usersettings',
            managers=[
                ('objects', base.acl.ACLManager()),
            ],
        ),
    ]
