# Generated by Django 5.2.7 on 2025-11-05 20:19

import base.acl
import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_company_managers_alter_usersettings_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('objects', base.acl.ACLManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.models.UserManager()),
                ('acl_objects', base.acl.ACLManager()),
            ],
        ),
    ]
