# Generated by Django 5.2.7 on 2025-11-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_company_managers_alter_usersettings_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                # Manager افتراضي فقط (بدون ACL)
                ('objects', models.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                # Manager افتراضي فقط (بدون ACL)
                ('objects', models.Manager()),
            ],
        ),
    ]
