# Generated by Django 5.2.7 on 2025-11-06 15:48

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_partner_managers_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('objects', base.models.ScopedACLManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.models.UserManager()),
                ('scoped_objects', base.models.ScopedACLManager()),
            ],
        ),
    ]
