# Generated by Django 5.2.7 on 2025-11-06 15:50

from django.db import migrations, models
import base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_partner_managers_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.models.UserManager()),
            ],
        ),
    ]
