# Generated by Django 5.2.7 on 2025-11-14 19:01

import base.acl
import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', base.acl.ACLManager()),
                ('acl_objects', base.acl.ACLManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('objects', base.models.ScopedACLManager()),
                ('acl_objects', base.acl.ACLManager()),
            ],
        ),
    ]
