# Generated by Django 5.2.7 on 2025-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_company_managers_alter_partner_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', models.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('objects', models.Manager()),
            ],
        ),
    ]
