# Generated by Django 5.2.7 on 2025-12-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Managed automatically via Partner hierarchy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='base.company'),
        ),
    ]
