# Generated by Django 5.2.7 on 2026-01-13 19:24

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='partner',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usersettings',
            managers=[
            ],
        ),
    ]
