# Generated by Django 5.2.6 on 2025-09-25 19:56

import datetime
import django.db.models.deletion
import skills.models.skill_type
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrResumeLineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=10)),
                ('is_course', models.BooleanField(default=False)),
                ('resume_line_type_properties_definition', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hr_resume_line_type',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='HrSkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('sequence', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=255)),
                ('color', models.IntegerField(default=skills.models.skill_type.default_color)),
                ('is_certification', models.BooleanField(default=False)),
                ('levels_count', models.IntegerField(default=0, help_text='Number of levels linked to this skill type')),
            ],
            options={
                'db_table': 'hr_skill_type',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HrSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('level_progress', models.IntegerField(help_text='0..100% mastery')),
                ('default_level', models.BooleanField(default=False)),
                ('technical_is_new_default', models.BooleanField(default=False)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_skill_level_set', to='skills.hrskilltype')),
            ],
            options={
                'db_table': 'hr_skill_level',
                'ordering': ['level_progress'],
            },
        ),
        migrations.CreateModel(
            name='HrSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=10)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.hrskilltype')),
            ],
            options={
                'db_table': 'hr_skill',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HrEmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.hrskill')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.hrskilllevel')),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.hrskilltype')),
            ],
            options={
                'db_table': 'hr_employee_skill',
                'ordering': ['skill_type_id', 'skill_level_id'],
            },
        ),
        migrations.CreateModel(
            name='HrResumeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('course_type', models.CharField(choices=[('external', 'External')], default='external', max_length=20)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('external_url', models.CharField(blank=True, max_length=1024)),
                ('certificate_filename', models.CharField(blank=True, max_length=255)),
                ('certificate_file', models.BinaryField(blank=True, null=True)),
                ('resume_line_properties', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_lines', to='hr.employee')),
                ('line_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_lines', to='skills.hrresumelinetype')),
            ],
            options={
                'db_table': 'hr_resume_line',
                'ordering': ['line_type_id', '-date_end', '-date_start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_end__isnull', True), ('date_start__lte', models.F('date_end')), _connector='OR'), name='chk_resume_line_dates_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='hrskilllevel',
            constraint=models.CheckConstraint(condition=models.Q(('level_progress__gte', 0), ('level_progress__lte', 100)), name='chk_skill_level_progress_0_100'),
        ),
    ]
