# Generated by Django 5.2.7 on 2025-10-17 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrResumeLineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sequence', models.IntegerField(default=10)),
                ('is_course', models.BooleanField(default=False)),
                ('properties_definition', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_resume_line_type',
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HrResumeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Title of the experience/course/education item.', max_length=255)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('course_type', models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], default='external', max_length=16)),
                ('external_url', models.URLField(blank=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='resume_certificates/')),
                ('certificate_filename', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resume_lines', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_lines', to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_lines', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('line_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume_lines', to='skills.hrresumelinetype')),
            ],
            options={
                'db_table': 'hr_resume_line',
                'ordering': ('-date_start', '-date_end', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HrSkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sequence', models.IntegerField(default=10)),
                ('color', models.IntegerField(default=1)),
                ('is_certification', models.BooleanField(default=False)),
                ('levels_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_skill_type',
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HrSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('level_progress', models.PositiveIntegerField(default=0)),
                ('default_level', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='skills.hrskilltype')),
            ],
            options={
                'db_table': 'hr_skill_level',
                'ordering': ('level_progress', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HrSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.hrskilltype')),
            ],
            options={
                'db_table': 'hr_skill',
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HrEmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='skills.hrskill')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='skills.hrskilllevel')),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='skills.hrskilltype')),
            ],
            options={
                'db_table': 'hr_employee_skill',
                'ordering': ('skill_type', 'skill', 'skill_level', 'valid_from', 'id'),
                'permissions': [('rate_skill', 'Can rate employee skill')],
            },
        ),
        migrations.AddIndex(
            model_name='hrresumelinetype',
            index=models.Index(fields=['active'], name='hr_resume_l_active_f4324c_idx'),
        ),
        migrations.AddIndex(
            model_name='hrresumeline',
            index=models.Index(fields=['employee'], name='hr_resume_l_employe_6963b6_idx'),
        ),
        migrations.AddIndex(
            model_name='hrresumeline',
            index=models.Index(fields=['line_type'], name='hr_resume_l_line_ty_9c69bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hrresumeline',
            index=models.Index(fields=['date_start', 'date_end'], name='hr_resume_l_date_st_d4339d_idx'),
        ),
        migrations.AddIndex(
            model_name='hrskilltype',
            index=models.Index(fields=['active'], name='hr_skill_ty_active_303fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='hrskilltype',
            index=models.Index(fields=['sequence', 'name'], name='hr_skill_ty_sequenc_980516_idx'),
        ),
        migrations.AddIndex(
            model_name='hrskilllevel',
            index=models.Index(fields=['skill_type'], name='hr_skill_le_skill_t_accc67_idx'),
        ),
        migrations.AddIndex(
            model_name='hrskilllevel',
            index=models.Index(fields=['level_progress'], name='hr_skill_le_level_p_752104_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrskilllevel',
            constraint=models.CheckConstraint(condition=models.Q(('level_progress__gte', 0), ('level_progress__lte', 100)), name='skill_level_progress_range'),
        ),
        migrations.AlterUniqueTogether(
            name='hrskilllevel',
            unique_together={('skill_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='hrskill',
            index=models.Index(fields=['active'], name='hr_skill_active_505478_idx'),
        ),
        migrations.AddIndex(
            model_name='hrskill',
            index=models.Index(fields=['skill_type'], name='hr_skill_skill_t_168688_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hrskill',
            unique_together={('skill_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='hremployeeskill',
            index=models.Index(fields=['employee'], name='hr_employee_employe_849de2_idx'),
        ),
        migrations.AddIndex(
            model_name='hremployeeskill',
            index=models.Index(fields=['skill'], name='hr_employee_skill_i_880da7_idx'),
        ),
        migrations.AddIndex(
            model_name='hremployeeskill',
            index=models.Index(fields=['skill_type'], name='hr_employee_skill_t_c37c07_idx'),
        ),
        migrations.AddIndex(
            model_name='hremployeeskill',
            index=models.Index(fields=['skill_level'], name='hr_employee_skill_l_d5ecb4_idx'),
        ),
    ]
