# Generated by Django 5.2.7 on 2025-11-01 20:39

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeeskill',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resumeline',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
    ]
