# Generated by Django 5.2.6 on 2025-09-28 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_birthday_employee_certificate_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hrresumeline',
            name='chk_resume_line_dates_order',
        ),
        migrations.RemoveConstraint(
            model_name='hrskilllevel',
            name='chk_skill_level_progress_0_100',
        ),
        migrations.AlterField(
            model_name='hremployeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='hrresumeline',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='hr/certificates/'),
        ),
        migrations.AlterField(
            model_name='hrresumeline',
            name='course_type',
            field=models.CharField(choices=[('external', 'External')], default='external', max_length=16),
        ),
        migrations.AlterField(
            model_name='hrresumeline',
            name='external_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='hrresumeline',
            name='line_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_lines', to='skills.hrresumelinetype'),
        ),
        migrations.AlterField(
            model_name='hrskill',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_ids', to='skills.hrskilltype'),
        ),
        migrations.AlterField(
            model_name='hrskilllevel',
            name='level_progress',
            field=models.IntegerField(help_text='Progress 0..100'),
        ),
        migrations.AlterField(
            model_name='hrskilllevel',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_level_ids', to='skills.hrskilltype'),
        ),
        migrations.AlterField(
            model_name='hrskilltype',
            name='levels_count',
            field=models.IntegerField(default=0),
        ),
    ]
