# Generated by Django 5.2.7 on 2025-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_employeeskill_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeeskill',
            managers=[
                # الرجوع إلى manager افتراضي فقط
                ('objects', models.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resumeline',
            managers=[
                # الرجوع إلى manager افتراضي فقط
                ('objects', models.Manager()),
            ],
        ),
    ]
