# Generated by Django 5.2.7 on 2025-12-18 18:18

import base.acl
import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_employeeskill_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeeskill',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
                ('acl', base.acl.ACLManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resumeline',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
                ('acl', base.acl.ACLManager()),
            ],
        ),
    ]
