# Generated by Django 5.2.7 on 2025-12-18 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_company_managers_alter_partner_managers'),
        ('hr', '0006_alter_employee_company'),
        ('skills', '0003_alter_employeeskill_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeskill',
            name='employeeskill_unique_employee_skill',
        ),
        migrations.RemoveConstraint(
            model_name='skilllevel',
            name='skilllevel_single_default_per_type',
        ),
        migrations.RemoveIndex(
            model_name='employeeskill',
            name='es_comp_emp_act_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeskill',
            name='es_type_lvl_idx',
        ),
        migrations.RemoveIndex(
            model_name='resumeline',
            name='rl_comp_emp_act_idx',
        ),
        migrations.RemoveIndex(
            model_name='resumeline',
            name='rl_type_act_idx',
        ),
        migrations.RemoveIndex(
            model_name='resumelinetype',
            name='resumelinetype_active_seq_idx',
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='skill_active_type_idx',
        ),
        migrations.AddConstraint(
            model_name='employeeskill',
            constraint=models.UniqueConstraint(fields=('company', 'employee', 'skill'), name='employeeskill_unique_company_employee_skill', violation_error_message='This employee already has this skill.'),
        ),
        migrations.AddConstraint(
            model_name='skilllevel',
            constraint=models.UniqueConstraint(condition=models.Q(('default_level', True)), fields=('skill_type',), name='skilllevel_single_default_per_type'),
        ),
    ]
