# Generated by Django 5.2.7 on 2026-01-01 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0013_employeeeducation'),
        ('skills', '0004_remove_employeeskill_employeeskill_unique_employee_skill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeskill',
            name='employeeskill_unique_company_employee_skill',
        ),
        migrations.AddConstraint(
            model_name='employeeskill',
            constraint=models.UniqueConstraint(fields=('employee', 'skill'), name='employeeskill_unique_employee_skill', violation_error_message='This employee already has this skill.'),
        ),
    ]
