# Generated by Django 5.2.7 on 2026-01-04 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_parent'),
        ('hr', '0013_employeeeducation'),
        ('skills', '0005_remove_employeeskill_employeeskill_unique_company_employee_skill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resumeline',
            constraint=models.UniqueConstraint(fields=('employee', 'line_type', 'name'), name='resumeline_unique_employee_type_name'),
        ),
    ]
