# Generated by Django 5.2.7 on 2026-01-07 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_employeeeducation'),
        ('skills', '0007_companyskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='hr.job')),
                ('min_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='skills.skilllevel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='skills.skill')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Required Skill',
                'verbose_name_plural': 'Job Required Skills',
                'ordering': ('job__name', 'skill__name'),
                'constraints': [models.UniqueConstraint(fields=('job', 'skill'), name='jobskill_unique_job_skill')],
            },
        ),
    ]
