# Generated by Django 5.2.7 on 2026-01-12 20:54

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_jobskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'ordering': ('employee__company__name', 'employee__name', 'skill_type__sequence', 'skill__name'), 'verbose_name': 'Employee Skill', 'verbose_name_plural': 'Employee Skills'},
        ),
        migrations.AlterModelManagers(
            name='employeeskill',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resumeline',
            managers=[
                ('objects', base.models.CompanyScopeManager()),
            ],
        ),
    ]
