# Generated by Django 5.2.7 on 2025-10-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shift_name', models.CharField(blank=True, max_length=255)),
                ('weekday', models.PositiveSmallIntegerField(default=0)),
                ('planned_from', models.TimeField(blank=True, null=True)),
                ('planned_to', models.TimeField(blank=True, null=True)),
                ('first_in', models.DateTimeField(blank=True, null=True)),
                ('last_out', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_leave_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_day_off', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('present', 'Present'), ('partial', 'Partial'), ('leave', 'Leave/Day Off'), ('weekend', 'Weekend'), ('no_schedule', 'No Schedule')], db_index=True, default='no_schedule', max_length=16)),
                ('calc_notes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'att_day',
                'ordering': ('employee_id', '-date'),
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], max_length=8)),
                ('ts', models.DateTimeField(help_text='Event timestamp in company timezone')),
                ('source', models.CharField(blank=True, default='manual', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'att_log',
                'ordering': ('employee_id', 'ts'),
            },
        ),
    ]
