# Generated by Django 5.2.7 on 2025-10-31 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='att_days', to='base.company'),
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_days', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='att_logs', to='base.company'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_logs', to='hr.employee'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['company', 'employee', 'date'], name='attday_c_e_d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['company', 'date', 'status'], name='attday_c_d_s_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceday',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['company', 'employee', 'ts'], name='attlog_c_e_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'ts'], name='attlog_e_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['in', 'out'])), name='attlog_kind_chk'),
        ),
    ]
